# slackpkg aliases
alias spkg="slackpkg"
alias spkgall="slackpkg upgrade-all"
alias spkgcheck="slackpkg check-updates"
alias spkgfind="slackpkg search"
alias spkgget="slackpkg install"
alias spkggpg="slackpkg update gpg"
alias spkgnew="slackpkg install-new"
alias spkgupdate="slackpkg update"
alias spkgredo="slackpkg reinstall"
alias spkgremove="slackpkg remove"
alias spkgrenew="slackpkg update gpg; slackpkg update"
alias spkgshow="slackpkg info"
